#Message Format: Popup, Tip, or Sidebar(expieramental)
Format: Tip
#Message
#The & symbol replaces the ยง symbol for color coding! Use {LINE} to go down to the next line!
Message: '&b&lWelcome to &cMy Server!'
